# Generated by Django 4.1.5 on 2023-01-20 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('content', models.CharField(max_length=1000, verbose_name='content')),
                ('type', models.CharField(choices=[('SF', 'SendFriend'), ('SC', 'SendCommunity'), ('SG', 'SendGroup'), ('AN', 'AdminNews')], max_length=200, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('content', models.CharField(max_length=1000, verbose_name='content')),
                ('type', models.CharField(choices=[('SF', 'SendFriend'), ('SC', 'SendCommunity'), ('SG', 'SendGroup'), ('AN', 'AdminNews')], max_length=200, verbose_name='type')),
                ('answer', models.BooleanField(default=False, verbose_name='answer')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_group_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_group_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendNotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('content', models.CharField(max_length=1000, verbose_name='content')),
                ('type', models.CharField(choices=[('SF', 'SendFriend'), ('SC', 'SendCommunity'), ('SG', 'SendGroup'), ('AN', 'AdminNews')], max_length=200, verbose_name='type')),
                ('answer', models.BooleanField(default=False, verbose_name='answer')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_friend_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_friend_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('content', models.CharField(max_length=1000, verbose_name='content')),
                ('type', models.CharField(choices=[('SF', 'SendFriend'), ('SC', 'SendCommunity'), ('SG', 'SendGroup'), ('AN', 'AdminNews')], max_length=200, verbose_name='type')),
                ('answer', models.BooleanField(default=False, verbose_name='answer')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_community_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_community_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
