# Generated by Django 4.1.5 on 2023-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('various', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotificationModel',
        ),
        migrations.AddField(
            model_name='communitynotificationmodel',
            name='check_notification',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
        migrations.AddField(
            model_name='friendnotificationsmodel',
            name='check_notification',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
        migrations.AddField(
            model_name='groupnotificationmodel',
            name='check_notification',
            field=models.BooleanField(default=False, verbose_name='check'),
        ),
    ]
