# Generated by Django 4.1.5 on 2023-01-20 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('various', '0002_delete_adminnotificationmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteNotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='time create')),
                ('content', models.CharField(max_length=1000, verbose_name='content')),
                ('type', models.CharField(choices=[('SF', 'SendFriend'), ('SC', 'SendCommunity'), ('SG', 'SendGroup'), ('AN', 'AdminNews')], max_length=200, verbose_name='type')),
                ('check_notification', models.BooleanField(default=False, verbose_name='check')),
                ('answer', models.BooleanField(default=False, verbose_name='answer')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_invite_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_invite_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='friendnotificationsmodel',
            name='recipient_user',
        ),
        migrations.RemoveField(
            model_name='friendnotificationsmodel',
            name='sender_friend',
        ),
        migrations.RemoveField(
            model_name='groupnotificationmodel',
            name='recipient_user',
        ),
        migrations.RemoveField(
            model_name='groupnotificationmodel',
            name='sender_group',
        ),
        migrations.DeleteModel(
            name='CommunityNotificationModel',
        ),
        migrations.DeleteModel(
            name='FriendNotificationsModel',
        ),
        migrations.DeleteModel(
            name='GroupNotificationModel',
        ),
    ]
