# Generated by Django 4.1.5 on 2023-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('various', '0003_invitenotificationsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitenotificationsmodel',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='time create'),
        ),
    ]
