# Generated by Django 4.1.5 on 2023-01-20 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_groupchatsmodel_groupmessagemodel_and_more'),
        ('community', '0006_alter_communitypostmodel_dislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('various', '0004_alter_invitenotificationsmodel_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitenotificationsmodel',
            name='sender_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_invite_notifications', to='community.communitymodel'),
        ),
        migrations.AddField(
            model_name='invitenotificationsmodel',
            name='sender_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_invite_notifications', to='discussion.groupchatsmodel'),
        ),
        migrations.AlterField(
            model_name='invitenotificationsmodel',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_invite_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
