# Generated by Django 4.1.5 on 2023-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('topic', models.CharField(max_length=200, verbose_name='topic')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(null=True, upload_to='community/post/%Y/%m/%d/', verbose_name='image')),
                ('like', models.PositiveBigIntegerField(verbose_name='like')),
                ('dislike', models.PositiveBigIntegerField(verbose_name='dislike')),
            ],
        ),
    ]
