# Generated by Django 4.1.5 on 2023-01-19 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0002_groupchatsmodel_groupmessagemodel_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymodel',
            name='topic',
        ),
        migrations.AddField(
            model_name='communitymodel',
            name='moderator',
            field=models.ManyToManyField(related_name='mod_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitymodel',
            name='subscribers',
            field=models.ManyToManyField(related_name='sub_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypostmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypostmodel',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_post', to='community.communitymodel'),
        ),
        migrations.AlterField(
            model_name='communitymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='CommunityInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='community/avatar/%Y/%m/%d/', verbose_name='avatar')),
                ('topic', models.CharField(max_length=200, null=True, verbose_name='topic')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_com', to=settings.AUTH_USER_MODEL, verbose_name='chapter')),
                ('chat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_info', to='discussion.chatsmodel', verbose_name='com_chat')),
            ],
        ),
        migrations.AddField(
            model_name='communitymodel',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_main', to='community.communityinfomodel', verbose_name='info'),
        ),
    ]
