# Generated by Django 4.1.5 on 2023-01-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_groupchatsmodel_groupmessagemodel_and_more'),
        ('community', '0002_remove_communitymodel_topic_communitymodel_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinfomodel',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_info', to='discussion.groupchatsmodel', verbose_name='com_chat'),
        ),
    ]
