# Generated by Django 4.1.5 on 2023-01-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_communityinfomodel_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymodel',
            old_name='id',
            new_name='myid',
        ),
    ]
