# Generated by Django 4.1.5 on 2023-01-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_myid_communitymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypostmodel',
            name='dislike',
            field=models.PositiveBigIntegerField(default=0, verbose_name='dislike'),
        ),
        migrations.AlterField(
            model_name='communitypostmodel',
            name='like',
            field=models.PositiveBigIntegerField(default=0, verbose_name='like'),
        ),
    ]
