# Generated by Django 4.1.5 on 2023-01-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfomodel',
            name='community',
        ),
        migrations.AlterField(
            model_name='profilepostmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='my_user.profileinfomodel', verbose_name='author'),
        ),
    ]
