# Generated by Django 4.1.5 on 2023-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_remove_profileinfomodel_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfomodel',
            name='subscribers',
            field=models.ManyToManyField(to='my_user.profileinfomodel'),
        ),
    ]
